# Generated by Django 4.1.1 on 2022-09-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='induction',
            name='author',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='induction',
            name='body',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AddField(
            model_name='induction',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
