# Generated by Django 4.1.1 on 2022-09-25 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_research_induction_author_induction_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='author',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='research',
            name='body',
            field=models.TextField(blank=True, max_length=30000),
        ),
        migrations.AddField(
            model_name='research',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='scriptsuggestions',
            name='author',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='scriptsuggestions',
            name='body',
            field=models.TextField(blank=True, max_length=30000),
        ),
        migrations.AddField(
            model_name='scriptsuggestions',
            name='title',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='induction',
            name='body',
            field=models.TextField(blank=True, max_length=30000),
        ),
    ]
