# Generated by Django 4.1.1 on 2022-09-25 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0004_preamble_stockscript_alter_induction_body_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScriptSuggestions',
            new_name='ScriptSuggestion',
        ),
    ]
