# Generated by Django 4.1.1 on 2022-09-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_rename_scriptsuggestions_scriptsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='induction',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='preamble',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='research',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='scriptsuggestion',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='stockscript',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
