# Generated by Django 4.1.1 on 2022-09-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0006_induction_slug_preamble_slug_research_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
