# Generated by Django 4.1.1 on 2022-12-04 12:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0007_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptsuggestion',
            name='geeks_field',
            field=ckeditor.fields.RichTextField(blank=True, max_length=300000),
        ),
    ]
