# Generated by Django 4.1.1 on 2022-12-18 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0008_gatewayprotect'),
        ('contents', '0009_research_geeks_field'),
    ]

    operations = [
    ]
