# Generated by Django 4.1.1 on 2023-01-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0010_merge_0008_gatewayprotect_0009_research_geeks_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='research',
            name='essential',
            field=models.BooleanField(default=False),
        ),
    ]
