# Generated by Django 4.1.1 on 2023-01-02 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0012_induction_essential_preamble_essential_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='induction',
            old_name='essential',
            new_name='_essential',
        ),
    ]
