# Generated by Django 4.1.1 on 2023-01-02 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0013_rename_essential_induction__essential'),
    ]

    operations = [
        migrations.AddField(
            model_name='induction',
            name='essential1',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
