# Generated by Django 4.1.1 on 2023-01-02 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0014_induction_essential1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='induction',
            old_name='essential1',
            new_name='essentia1',
        ),
    ]
