# Generated by Django 4.1.1 on 2023-01-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0016_preamble_essentia1_research_essentia1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='induction',
            name='_essential',
        ),
        migrations.RemoveField(
            model_name='preamble',
            name='essential',
        ),
        migrations.RemoveField(
            model_name='research',
            name='essential',
        ),
        migrations.RemoveField(
            model_name='scriptsuggestion',
            name='essential',
        ),
        migrations.RemoveField(
            model_name='stockscript',
            name='essential',
        ),
        migrations.AddField(
            model_name='preamble',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
