# Generated by Django 4.1.6 on 2023-02-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0017_remove_induction__essential_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preamble',
            name='essentia1',
        ),
    ]
