# Generated by Django 4.1.6 on 2023-02-12 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0018_remove_preamble_essentia1'),
    ]

    operations = [
        migrations.AddField(
            model_name='induction',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='research',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scriptsuggestion',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stockscript',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
