# Generated by Django 5.2.7 on 2025-11-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0020_nytimes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TorStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('is_published', models.BooleanField(default=True)),
                ('essentia1', models.BooleanField(blank=True, default=False)),
                ('author', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('body', models.TextField(blank=True, max_length=300000)),
            ],
        ),
        migrations.CreateModel(
            name='WSJournal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('is_published', models.BooleanField(default=True)),
                ('essentia1', models.BooleanField(blank=True, default=False)),
                ('author', models.CharField(blank=True, max_length=300)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('body', models.TextField(blank=True, max_length=300000)),
            ],
        ),
    ]
