# Generated by Django 5.2.7 on 2025-11-15 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0021_torstar_wsjournal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssortedPeriodicals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('essentia1', models.BooleanField(blank=True, default=False)),
                ('address', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
