# Generated by Django 5.2.7 on 2025-11-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0022_assortedperiodicals'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssortedLiterature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(blank=True, max_length=300)),
                ('author_last_name', models.CharField(blank=True, max_length=300)),
                ('publication_year', models.CharField(blank=True, max_length=300)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('title', models.CharField(blank=True, max_length=300)),
            ],
        ),
    ]
