# Generated by Django 5.2.7 on 2025-11-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0023_assortedliterature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assortedperiodicals',
            name='essentia1',
        ),
        migrations.AddField(
            model_name='assortedperiodicals',
            name='author_last_name',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='assortedperiodicals',
            name='media_type',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='assortedperiodicals',
            name='publication_year',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
