# Generated by Django 6.0 on 2026-02-12 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0025_binaurals'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE contents_scriptsuggestion DROP COLUMN IF EXISTS geeks_field;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]