# Generated by Django 6.1.1 on 2026-09-26 06:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0027_drop_research_geeks_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assortedliterature',
            options={'verbose_name': 'Assorted Literature', 'verbose_name_plural': 'Assorted Literature'},
        ),
        migrations.AlterModelOptions(
            name='assortedperiodicals',
            options={'verbose_name': 'Assorted Periodicals', 'verbose_name_plural': 'Assorted Periodicals'},
        ),
        migrations.AlterModelOptions(
            name='binaurals',
            options={'verbose_name': 'Binaurals', 'verbose_name_plural': 'Binaurals'},
        ),
        migrations.AlterModelOptions(
            name='induction',
            options={'verbose_name': 'Induction', 'verbose_name_plural': 'Inductions'},
        ),
        migrations.AlterModelOptions(
            name='nytimes',
            options={'verbose_name': 'NY Times', 'verbose_name_plural': 'NY Times'},
        ),
        migrations.AlterModelOptions(
            name='preamble',
            options={'verbose_name': 'Preamble', 'verbose_name_plural': 'Preambles'},
        ),
        migrations.AlterModelOptions(
            name='research',
            options={'verbose_name': 'Research', 'verbose_name_plural': 'Research'},
        ),
        migrations.AlterModelOptions(
            name='scriptsuggestion',
            options={'verbose_name': 'Scripting (Custom)', 'verbose_name_plural': 'Scripting (Custom)'},
        ),
        migrations.AlterModelOptions(
            name='stockscript',
            options={'verbose_name': 'Scripting (Stock)', 'verbose_name_plural': 'Scripting (Stock)'},
        ),
        migrations.AlterModelOptions(
            name='torstar',
            options={'verbose_name': 'Toronto Star', 'verbose_name_plural': 'Toronto Star'},
        ),
        migrations.AlterModelOptions(
            name='wsjournal',
            options={'verbose_name': 'WSJ', 'verbose_name_plural': 'WSJ'},
        ),
        migrations.AddField(
            model_name='induction',
            name='excluded_users',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nytimes',
            name='excluded_users',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preamble',
            name='excluded_users',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='research',
            name='excluded_users',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scriptsuggestion',
            name='excluded_users',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockscript',
            name='excluded_users',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='torstar',
            name='excluded_users',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wsjournal',
            name='excluded_users',
            field=models.ManyToManyField(blank=True, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
