# Generated by Django 6.1.1 on 2026-09-30 03:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0030_add_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assortedliterature',
            name='publication_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='binaurals',
            name='publication_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='induction',
            name='publication_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='preamble',
            name='publication_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='research',
            name='publication_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='scriptsuggestion',
            name='publication_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='stockscript',
            name='publication_date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
