# Generated by Django 5.2.7 on 2025-11-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables_question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoggle',
            name='linkedin',
            field=models.CharField(default='', max_length=50),
        ),
    ]
