# Generated by Django 5.2.7 on 2025-11-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('variables_question', '0002_alter_authtoggle_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoggle',
            name='github',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='authtoggle',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
