# Generated by Django 4.1.1 on 2022-11-21 11:06

import django.contrib.admin.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('contents', '0008_gatewayprotect'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='scriptsuggestion',
            managers=[
                ('objects', django.contrib.admin.models.LogEntryManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='scriptsuggestion',
            name='id',
        ),
        migrations.AddField(
            model_name='scriptsuggestion',
            name='logentry_ptr',
            field=models.OneToOneField(auto_created=True, default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='admin.logentry'),
            preserve_default=False,
        ),
    ]
