# Generated by Django 4.1.1 on 2023-01-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0011_research_essential'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='essential',
            field=models.BooleanField(blank=False, default=False),
        ),
    ]
