# Generated by Django 4.1.1 on 2023-01-02 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0013_alter_research_essential'),
    ]

    operations = [
        migrations.AddField(
            model_name='induction',
            name='essential',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='preamble',
            name='essential',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='scriptsuggestion',
            name='essential',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='stockscript',
            name='essential',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
